package cz.airbank.cucumber.reports.dao.entity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * Entity representing test suite execution.
 * Test suite execution usually contains functional tests for part of business functionality.
 *
 * @author David Passler
 */
@Document(collection = "test_suite")
public class TestSuiteExecution implements Serializable {

    private static final long serialVersionUID = -5523642740555337998L;

    @Id
    private String id;
    private List<FeatureRun> featureRuns;
    private DaoTestSuiteMetadata metadata;

    /**
     * Unique ID that identifies the build. Is generated by {@link org.springframework.data.mongodb.core.convert.MappingMongoConverter}
     * and unique globally in database. As value {@link org.bson.types.ObjectId} is assigned.
     *
     * @see org.bson.types.ObjectId
     * @see org.springframework.data.mongodb.core.convert.MappingMongoConverter
     */
    public String getId() {
        return id;
    }

    /**
     * All executed Cucumber tests within test execution.
     */
    public List<FeatureRun> getFeatureRuns() {
        if (featureRuns == null) {
            featureRuns = new ArrayList<>();
        }

        return featureRuns;
    }

    public void setFeatureRuns(List<FeatureRun> featureRuns) {
        this.featureRuns = featureRuns;
    }

    /**
     * Metadata about test suite execution
     */
    public DaoTestSuiteMetadata getMetadata() {
        return metadata;
    }

    public void setMetadata(DaoTestSuiteMetadata metadata) {
        this.metadata = metadata;
    }

    @Override
    public String toString() {
        return "TestSuiteExecution{" +
                "id='" + id + '\'' +
                ", featureRuns=" + featureRuns +
                ", metadata=" + metadata +
                '}';
    }
}
